In [1]:
print("heollo")

heollo


In [2]:
import numpy as np
import pandas as pd

data = {
    "Feature1": [2.5, 0.5, 2.2, 1.9, 3.1, 2.3, 2.0, 1.0, 1.5, 1.1],
    "Feature2": [2.4, 0.7, 2.9, 2.2, 3.0, 2.7, 1.6, 1.1, 1.6, 0.9]
}

df = pd.DataFrame(data)
print("Original Data:\n", df)


Original Data:
    Feature1  Feature2
0       2.5       2.4
1       0.5       0.7
2       2.2       2.9
3       1.9       2.2
4       3.1       3.0
5       2.3       2.7
6       2.0       1.6
7       1.0       1.1
8       1.5       1.6
9       1.1       0.9


In [3]:
X = df.values

mean = np.mean(X, axis=0)
X_centered = X - mean

print("\nMean:\n", mean)
print("\nCentered Data:\n", X_centered)



Mean:
 [1.81 1.91]

Centered Data:
 [[ 0.69  0.49]
 [-1.31 -1.21]
 [ 0.39  0.99]
 [ 0.09  0.29]
 [ 1.29  1.09]
 [ 0.49  0.79]
 [ 0.19 -0.31]
 [-0.81 -0.81]
 [-0.31 -0.31]
 [-0.71 -1.01]]


In [4]:
cov_matrix = np.cov(X_centered.T)

print("\nCovariance Matrix:\n", cov_matrix)



Covariance Matrix:
 [[0.61655556 0.61544444]
 [0.61544444 0.71655556]]


In [5]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)



Eigenvalues:
 [0.0490834  1.28402771]

Eigenvectors:
 [[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


In [6]:
idx = np.argsort(eigenvalues)[::-1]

eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

print("\nSorted Eigenvalues:\n", eigenvalues)
print("\nSorted Eigenvectors:\n", eigenvectors)



Sorted Eigenvalues:
 [1.28402771 0.0490834 ]

Sorted Eigenvectors:
 [[-0.6778734  -0.73517866]
 [-0.73517866  0.6778734 ]]


In [7]:
k = 1
principal_components = eigenvectors[:, :k]

print("\nPrincipal Component:\n", principal_components)



Principal Component:
 [[-0.6778734 ]
 [-0.73517866]]


In [8]:
X_reduced = X_centered @ principal_components

print("\nReduced Data (1D representation):\n", X_reduced)



Reduced Data (1D representation):
 [[-0.82797019]
 [ 1.77758033]
 [-0.99219749]
 [-0.27421042]
 [-1.67580142]
 [-0.9129491 ]
 [ 0.09910944]
 [ 1.14457216]
 [ 0.43804614]
 [ 1.22382056]]


In [11]:
explained_variance_ratio = eigenvalues / np.sum(eigenvalues)
k = 1
print("Information retained:", explained_variance_ratio[:k].sum() * 100)


Information retained: 96.3181314348646
